apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  loadBalancerIP: 35.231.254.102
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app-jupyter
